title: 2. semester på Cphbusiness
theme: just-the-docs
description: Diverse undervisningsmaterialer på 2. semester datamatiker uddannelsen på Cphbusiness
url: https://dat2Cph.github.io
logo: '/assets/images/cphbusiness_dark.png'
favicon_ico: '/assets/images/favicon.ico'
aux_links:
  Repository: https://github.com/dat2Cph/content
nav_enabled: true
heading_anchors: true
search_enabled: true
ga_tracking: G-BYSHS79QFS
plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: false

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: 'Top'

# For copy button on code
enable_copy_code_button: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - '*.gemspec'
  - '*.gem'
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/
