title: Kursusindhold 2. semester på Cphbusiness
description: Diverse undervisningsmaterialer på 2. semester datamatiker uddannelsen på Cphbusiness
theme: just-the-docs

url: https://dat2Cph.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
