title: 2. semester på Cphbusiness
theme: just-the-docs
description: Diverse undervisningsmaterialer på 2. semester datamatiker uddannelsen på Cphbusiness
url: https://dat2Cph.github.io
aux_links:
  Repository: https://github.com/dat2Cph/content
nav_enabled: true
heading_anchors: true
search_enabled: true
permalink: /:path/:basename.html
plugins:
  - jekyll-relative-links
