title: 2. semester på Cphbusiness
theme: just-the-docs
description: Diverse undervisningsmaterialer på 2. semester datamatiker uddannelsen på Cphbusiness
url: https://dat2Cph.github.io
logo: '/assets/images/cphbusiness.png'
favicon_ico: '/assets/images/favicon.ico'
aux_links:
  Repository: https://github.com/dat2Cph/content
nav_enabled: true
heading_anchors: true
search_enabled: true
plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: false
